format:
	# 如果你要取消检查，在文件开头加 # ruff: noqa
	# doc https://github.com/astral-sh/ruff
	#pip3 install ruff~=0.8.2
	ruff format . --respect-gitignore --line-length 150 --target-version py39

static_check:
	#pip3 install ruff~=0.8.2
	# 可以用ruff check . --fix 快速修复
	ruff check .

static_check_fix:
	#pip3 install ruff~=0.8.2
	ruff check . --fix
